server:
  port: 8080

spring:
  application:
    name: gateway-edge-server
eureka:
  instance:
    hostname: 34.66.153.219
    port: 8761
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/