server:
  port: 8891
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8890/oauth/check_token/
    client:
      client-id: fooClientId
      client-secret: secret
spring:
  application:
    name: authenticatio-resource-service
  datasource:
    url: jdbc:mysql://localhost:3306/authen
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
eureka:
  instance:
    hostname: 34.66.153.219
    port: 8761
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
logging:
  level:
    org:
      springframework:
        web: DEBUG