server:
  port: 9090
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token/
    client:
      client-id: fooClientId
      client-secret: secret
spring:
  application:
    name: resourceserv-test-service
eureka:
  instance:
    hostname: localhost
    port: 8761
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/