security:
  oauth2:
    resource:
      token-info-uri: http://172.20.10.3:8888/oauth/check_token/
    client:
      client-id: fooClientId
      client-secret: secret
spring:
   application:
      name: event-service
   profiles:
      active: default
   cloud:
      config:
         enabled: true

eureka:
   instance:
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://34.66.153.219:8761/eureka/
