
spring:
   application:
      name: myevent-service
   profiles:
      active: default
   cloud:
      config:
         enabled: true

eureka:
   instance:
      hostname: 35.236.184.82
      preferIpAddress: true
      port: 8761
      ipAddress: 35.247.175.250
      
   client:
      serviceUrl:
         defaultZone: http://34.66.153.219:8761/eureka/
      
server:
   port: 8000
