eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
   server:
      waitTimeInMsWhenSyncEmpty: 5
server:
   port: 8761
spring:
   cloud:
      inetutils:
         ignoredInterfaces:
            - nic0
            - default
         # preferredNetworks:
         #    - 10.0.0